name: video_describe
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pillow
  - ffmpeg
  - pip
  - cpuonly
  - pytorch
  - torchvision
  - torchaudio
  - opencv
  - pip:
    - ftfy
    - regex
    - tqdm
    - whisper-timestamped
    - onnxruntime
    - google-cloud-speech
    - openai
    - fastapi
    - uvicorn
    - python-dotenv
    - pydantic
    - boto3
    - gtts
    - yt-dlp
    - youtube-transcript-api
    - bitsandbytes
    - git+https://github.com/huggingface/transformers
    - soundfile
    - librosa
    - pydub
    - accelerate
    - jiwer
    - google-genai
    - qwen-vl-utils[decord]